version: "3"

tasks:
  dev:
    cmds:
      - bun run build:css
      - templ generate
      - go run main.go
  build:
    cmds:
      - go build -o ./bin/web main.go
    desc: "Build the Go project"
  # test:
  #   cmds:
  #     - go test ./...
  #   desc: "Run tests"

  docker-build:
    cmds:
      - docker build -t web .

  docker-run:
    cmds:
      - docker run -p 8080:8080 web
  lint:
    cmds:
      - golangci-lint run
    desc: "Lint the code"

  clean:
    cmds:
      - rm -rf myapp
    desc: "Clean the build artifacts"
